# This is a basic workflow to help you get started with Actions

name: Update CodeBuild Images

# This is what triggers the workflow
on: 
#   schedule:
#     - cron: '0 0 * * *' # This will tell the workflow to run every day at midnight


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Load Cache
        uses: actions/cache@v2.1.3
        with:
          path: ./hash-data.txt
          key: REMOTE_HASH
      - name: Compare Master Branch Commit with Last Checked Commit
        run: |
          REMOTE_HASH=$(git ls-remote https://github.com/aws/aws-codebuild-docker-images.git refs/heads/master | cut -f 1 )
          LAST_KNOWN_HASH=$(cat hash-data.txt)
          echo "REMOTE_HASH=${REMOTE_HASH}"
          echo "LAST_KNOWN_HASH=${LAST_KNOWN_HASH}
          if [[ ${REMOTE_HASH} == ${LAST_KNOWN_HASH} ]]; then
             echo "::set-env name=NEW_COMMITS::false"
          else
            echo "::set-env name=NEW_COMMITS::true"
          fi
          echo "${REMOTE_HASH}" > hash-data.txt
      - name: Update Cache
        uses: actions/cache@v2.1.3
        with:
          path: ./hash-data.txt
          key: REMOTE_HASH

          
  trigger-code-build:
    needs:  check-for-changes
    if: env.NEW_COMMITS == "true"
    runs-on: ubuntu-latest
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # AWS Access Key ID. This input is required if running in the GitHub hosted environment. It is optional if running in a self-hosted environment that already has AWS credentials, for example on an EC2 instance.
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          # AWS Secret Access Key. This input is required if running in the GitHub hosted environment. It is optional if running in a self-hosted environment that already has AWS credentials, for example on an EC2 instance.
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          # AWS Region, e.g. us-east-2
          aws-region: us-east-1
          # Whether to set the AWS account ID for these credentials as a secret value, so that it is masked in logs. Valid values are 'true' and 'false'. Defaults to true
          mask-aws-account-id: true
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1.0.3
        with:
          # AWS CodeBuild Project Name
          project-name: CodeBuildImageBuilder-AL2-x86_64-Standard
        
          
